<?php
// Contenu des pages « Sur-mesure » — une entrée par univers.
return [
    'hotellerie' => [
        'title' => 'Hôtellerie',
        'kicker' => 'Sur-mesure · Hôtels & résidences',
        'lead' => "Une chambre d'hôtel réussie se juge à une chose : la qualité du sommeil qu'elle offre. Nous équipons les hôtels, chambres d'hôtes et résidences de tourisme de Côte d'Ivoire avec du mobilier et de la literie pensés pour durer et faire revenir les clients.",
        'image' => 'assets/img/blog/furniture-4.jpg',
        'image_alt' => 'Matelas Mobilier Addict pour chambre d’hôtel',
        'story_title' => "L'expérience commence au premier regard",
        'story' => "Quand votre client pousse la porte de sa chambre, il juge en quelques secondes : la netteté du linge, la fermeté du matelas, la sensation des oreillers. Chaque détail compte. Mobilier Addict vous accompagne de la chambre standard à la suite premium, avec des gammes cohérentes qui donnent une identité à votre établissement — sans exploser votre budget.",
        'modeles' => [
            ['name' => 'Chambre Essentielle', 'desc' => "Le duo gagnant des petites structures : matelas Addict ferme, oreillers confort, parures résistantes aux lavages fréquents.", 'img' => 'assets/img/blog/furniture-1.jpg'],
            ['name' => 'Chambre Signature', 'desc' => "L'équilibre hôtelier : matelas Luxury, double jeu d'oreillers, couettes gonflantes et finitions soignées.", 'img' => 'assets/img/blog/furniture-6.jpg'],
            ['name' => 'Suite Premium', 'desc' => "L'expérience haut de gamme : grand confort, textile doux au toucher, accessoires de chambre assortis.", 'img' => 'assets/img/blog/furniture-8.jpg'],
        ],
        'equipement' => [
            ['Matelas hôteliers', 'matelas.php', 'Matelas fermes et durables, dimensions standard ou king size.'],
            ['Oreillers & taies', 'oreillers-et-taies.php', 'Confort moelleux, taies interchangeables pour rotation rapide.'],
            ['Draps & couettes', 'drap-et-couettes.php', 'Linge de lit résistant, pensé pour les cycles hôteliers.'],
            ['Mobilier de chambre', 'mobilier-accessoire.php', 'Têtes de lit, chevets, rangement et petit mobilier.'],
            ['Électroménager', 'electromenager.php', 'Petit équipement pour chambres et espaces communs.'],
        ],
        'gros' => "Vous équipez 10, 50 ou 200 chambres ? Nous préparons une commande groupée adaptée à votre planning d'ouverture ou de rénovation : un seul interlocuteur, un devis détaillé, des livraisons échelonnées possibles à Abidjan et en intérieur du pays.",
    ],
    'appartement-meuble' => [
        'title' => 'Appartement meublé',
        'kicker' => 'Sur-mesure · Bail & résidences meublées',
        'lead' => "Un appartement meublé prêt à louer doit séduire en une visite. Nous livrons des ensembles complets et cohérents — literie, mobilier, électroménager — pour que vos biens se louent vite et que vos locataires s'y sentent chez eux.",
        'image' => 'assets/img/about/about-hero.jpg',
        'image_alt' => 'Parure de lit dans un appartement meublé',
        'story_title' => "La première visite décide de tout",
        'story' => "Un locataire potentiel ne calcule pas le prix du mobilier : il imagine sa vie. Une chambre lumineuse avec une literie neuve et une déco harmonieuse transforme une simple visite en signature. Nous constituons des packs « clé en main » adaptés à chaque budget, du studio étudiant au trois-pièces familial.",
        'modeles' => [
            ['name' => 'Pack Locatif Essentiel', 'desc' => "Le nécessaire pour louer vite : lit, matelas, parure, rangement et petit électroménager.", 'img' => 'assets/img/blog/furniture-8.jpg'],
            ['name' => 'Pack Standing', 'desc' => "Un niveau au-dessus pour la location meublée haut de gamme : literie confort, mobilier design.", 'img' => 'assets/img/blog/furniture-6.jpg'],
            ['name' => 'Pack Résidence', 'desc' => "Pour les gérants de plusieurs appartements : gammes identiques, stocks de remplacement faciles.", 'img' => 'assets/img/blog/furniture-4.jpg'],
        ],
        'equipement' => [
            ['Literie complète', 'matelas.php', 'Matelas, oreillers et parures coordonnées par chambre.'],
            ['Draps & couettes', 'drap-et-couettes.php', 'Linge de remplacement prévu dès la livraison.'],
            ['Mobilier', 'mobilier-accessoire.php', 'Table, chaises, rangement, bureau selon la surface.'],
            ['Électroménager', 'electromenager.php', 'Froid, son et petit équipement du quotidien.'],
            ['Accessoires déco', 'mobilier-accessoire.php', 'Les finitions qui font la différence en photo d’annonce.'],
        ],
        'gros' => "Propriétaire de plusieurs lots ou gestionnaire de résidence ? Commandez par série : gammes homogènes, facturation groupée, renouvellement facilité quand un appartement se libère. Demandez votre pack personnalisé.",
    ],
    'studio' => [
        'title' => 'Studio',
        'kicker' => 'Sur-mesure · Studios & petits espaces',
        'lead' => "Un studio se joue au centimètre près. Nous composons des ensembles compacts et malins — bonne literie, rangement utile, petit électroménager — pour que le premier logement soit déjà un vrai chez-soi.",
        'image' => 'assets/img/blog/furniture-5.jpg',
        'image_alt' => 'Oreiller confort pour studio',
        'story_title' => "Petit espace, grand confort",
        'story' => "Premier appartement, résidence étudiante ou pied-à-terre : le studio exige des choix justes. Un bon matelas reste la priorité — c'est lui qui transforme 20 m² en lieu de repos réel. Nous privilégions le malin : literie 1 ou 2 places, mobilier compact, électroménager de petite dimension.",
        'modeles' => [
            ['name' => 'Studio Étudiant', 'desc' => "L'essentiel malin : matelas 1 place, oreiller confort, parure facile d'entretien.", 'img' => 'assets/img/blog/furniture-1.jpg'],
            ['name' => 'Studio Actif', 'desc' => "Pour les jeunes professionnels : literie 2 places, coin bureau, rangement optimisé.", 'img' => 'assets/img/about/about-hero.jpg'],
            ['name' => 'Pied-à-terre', 'desc' => "Le confort d'un second chez-soi : literie douillette, textile doux, petit électroménager.", 'img' => 'assets/img/blog/furniture-5.jpg'],
        ],
        'equipement' => [
            ['Matelas compacts', 'matelas.php', '1 ou 2 places, confort ferme ou moelleux.'],
            ['Oreillers & taies', 'oreillers-et-taies.php', 'Gammes Basiques et Confort pour petits budgets.'],
            ['Draps 1 place', 'drap-et-couettes.php', 'Parures adaptées aux lits simples.'],
            ['Rangement & bureau', 'mobilier-accessoire.php', 'Meubles compacts et multifonctions.'],
            ['Petit électroménager', 'electromenager.php', 'Mini froid, audio et accessoires.'],
        ],
        'gros' => "Résidence étudiante, cité universitaire ou promoteur de studios ? Équipez vos logements en série avec une gamme identique : commande groupée, prix dégressifs discutés, livraison par lot.",
    ],
    'famille' => [
        'title' => 'Famille',
        'kicker' => 'Sur-mesure · Maisons familiales',
        'lead' => "Une maison familiale, ce sont des matelas pour tous les âges, du linge qui survit aux dimanches et des meubles qui grandissent avec les enfants. Nous équipons toute la maison, de la chambre parentale à celle des petits.",
        'image' => 'assets/img/slideshow/f3.jpg',
        'image_alt' => 'Couette familiale Mobilier Addict',
        'story_title' => "Des nuits tranquilles pour toute la maison",
        'story' => "Chaque membre de la famille dort différemment : soutien ferme pour les parents, confort douillet pour les enfants, literie pratique pour la chambre d'amis. Plutôt qu'un achat au coup par coup, nous composons un équipement harmonieux qui dure des années — et qui rend chaque chambre accueillante.",
        'modeles' => [
            ['name' => 'Chambre Parentale', 'desc' => "Le confort des grandes nuits : grand matelas, oreillers extra confort, parures élégantes.", 'img' => 'assets/img/slideshow/f3.jpg'],
            ['name' => 'Chambre Enfants', 'desc' => "Des matelas adaptés et du linge résistant, pensé pour les lessives fréquentes.", 'img' => 'assets/img/blog/furniture-1.jpg'],
            ['name' => 'Chambre d’amis', 'desc' => "Accueillir sans se ruiner : literie confortable, polyvalente et facile à entretenir.", 'img' => 'assets/img/blog/furniture-4.jpg'],
        ],
        'equipement' => [
            ['Matelas par âge', 'matelas.php', 'Ferme, équilibré ou moelleux selon chacun.'],
            ['Oreillers & taies', 'oreillers-et-taies.php', 'Du Basique à l’Ultra confort pour toute la famille.'],
            ['Draps & couettes', 'drap-et-couettes.php', 'Toutes dimensions : 1, 2 et 3 places.'],
            ['Mobilier familial', 'mobilier-accessoire.php', 'Salon, tables, chaises et rangement.'],
            ['Électroménager', 'electromenager.php', 'Froid, son et audio pour le quotidien.'],
        ],
        'gros' => "Famille nombreuse, famille d'accueil ou maison à équiper d'un coup ? Le pack Famille regroupe toutes les chambres en une seule commande : moins d'allers-retours, une facture claire, un accompagnement personnalisé.",
    ],
];
